package com.yunsu.greendao.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PRODUCT_BASE".
 */
public class ProductBase {

    private Long id;
    private String productNumber;
    private String name;

    public ProductBase() {
    }

    public ProductBase(Long id) {
        this.id = id;
    }

    public ProductBase(Long id, String productNumber, String name) {
        this.id = id;
        this.productNumber = productNumber;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getProductNumber() {
        return productNumber;
    }

    public void setProductNumber(String productNumber) {
        this.productNumber = productNumber;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
