package com.yunsu.greendao.dao;

import android.database.sqlite.SQLiteDatabase;

import com.yunsu.greendao.dao.MaterialDao;
import com.yunsu.greendao.dao.OrderDao;
import com.yunsu.greendao.dao.PackDao;
import com.yunsu.greendao.entity.Material;
import com.yunsu.greendao.entity.Order;
import com.yunsu.greendao.entity.Pack;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig orderDaoConfig;
    private final DaoConfig materialDaoConfig;
    private final DaoConfig packDaoConfig;

    private final OrderDao orderDao;
    private final MaterialDao materialDao;
    private final PackDao packDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        orderDaoConfig = daoConfigMap.get(OrderDao.class).clone();
        orderDaoConfig.initIdentityScope(type);

        materialDaoConfig = daoConfigMap.get(MaterialDao.class).clone();
        materialDaoConfig.initIdentityScope(type);

        packDaoConfig = daoConfigMap.get(PackDao.class).clone();
        packDaoConfig.initIdentityScope(type);

        orderDao = new OrderDao(orderDaoConfig, this);
        materialDao = new MaterialDao(materialDaoConfig, this);
        packDao = new PackDao(packDaoConfig, this);

        registerDao(Order.class, orderDao);
        registerDao(Material.class, materialDao);
        registerDao(Pack.class, packDao);
    }
    
    public void clear() {
        orderDaoConfig.getIdentityScope().clear();
        materialDaoConfig.getIdentityScope().clear();
        packDaoConfig.getIdentityScope().clear();
    }

    public OrderDao getOrderDao() {
        return orderDao;
    }

    public MaterialDao getMaterialDao() {
        return materialDao;
    }

    public PackDao getPackDao() {
        return packDao;
    }

}
