package com.yunsu.greendao.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.yunsu.greendao.entity.Material;

import com.yunsu.greendao.entity.Pack;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PACK".
*/
public class PackDao extends AbstractDao<Pack, Long> {

    public static final String TABLENAME = "PACK";

    /**
     * Properties of entity Pack.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PackKey = new Property(1, String.class, "packKey", false, "PACK_KEY");
        public final static Property ActionId = new Property(2, String.class, "actionId", false, "ACTION_ID");
        public final static Property Agency = new Property(3, String.class, "agency", false, "AGENCY");
        public final static Property Status = new Property(4, String.class, "status", false, "STATUS");
        public final static Property SaveTime = new Property(5, String.class, "saveTime", false, "SAVE_TIME");
        public final static Property Count = new Property(6, Integer.class, "count", false, "COUNT");
        public final static Property Type = new Property(7, String.class, "type", false, "TYPE");
        public final static Property MaterialId = new Property(8, Long.class, "materialId", false, "MATERIAL_ID");
    };

    private DaoSession daoSession;

    private Query<Pack> material_PacksQuery;

    public PackDao(DaoConfig config) {
        super(config);
    }
    
    public PackDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PACK\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"PACK_KEY\" TEXT NOT NULL ," + // 1: packKey
                "\"ACTION_ID\" TEXT," + // 2: actionId
                "\"AGENCY\" TEXT," + // 3: agency
                "\"STATUS\" TEXT," + // 4: status
                "\"SAVE_TIME\" TEXT," + // 5: saveTime
                "\"COUNT\" INTEGER," + // 6: count
                "\"TYPE\" TEXT," + // 7: type
                "\"MATERIAL_ID\" INTEGER);"); // 8: materialId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PACK\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Pack entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getPackKey());
 
        String actionId = entity.getActionId();
        if (actionId != null) {
            stmt.bindString(3, actionId);
        }
 
        String agency = entity.getAgency();
        if (agency != null) {
            stmt.bindString(4, agency);
        }
 
        String status = entity.getStatus();
        if (status != null) {
            stmt.bindString(5, status);
        }
 
        String saveTime = entity.getSaveTime();
        if (saveTime != null) {
            stmt.bindString(6, saveTime);
        }
 
        Integer count = entity.getCount();
        if (count != null) {
            stmt.bindLong(7, count);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(8, type);
        }
 
        Long materialId = entity.getMaterialId();
        if (materialId != null) {
            stmt.bindLong(9, materialId);
        }
    }

    @Override
    protected void attachEntity(Pack entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Pack readEntity(Cursor cursor, int offset) {
        Pack entity = new Pack( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // packKey
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // actionId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // agency
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // status
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // saveTime
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // count
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // type
            cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8) // materialId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Pack entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPackKey(cursor.getString(offset + 1));
        entity.setActionId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAgency(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setStatus(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setSaveTime(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setCount(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setType(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setMaterialId(cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Pack entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Pack entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "packs" to-many relationship of Material. */
    public List<Pack> _queryMaterial_Packs(Long materialId) {
        synchronized (this) {
            if (material_PacksQuery == null) {
                QueryBuilder<Pack> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.MaterialId.eq(null));
                material_PacksQuery = queryBuilder.build();
            }
        }
        Query<Pack> query = material_PacksQuery.forCurrentThread();
        query.setParameter(0, materialId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getMaterialDao().getAllColumns());
            builder.append(" FROM PACK T");
            builder.append(" LEFT JOIN MATERIAL T0 ON T.\"MATERIAL_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Pack loadCurrentDeep(Cursor cursor, boolean lock) {
        Pack entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Material material = loadCurrentOther(daoSession.getMaterialDao(), cursor, offset);
        entity.setMaterial(material);

        return entity;    
    }

    public Pack loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Pack> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Pack> list = new ArrayList<Pack>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Pack> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Pack> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
