package com.yunsu.greendao.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.yunsu.greendao.entity.Material;
import com.yunsu.greendao.entity.Pack;

import com.yunsu.greendao.dao.MaterialDao;
import com.yunsu.greendao.dao.PackDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig materialDaoConfig;
    private final DaoConfig packDaoConfig;

    private final MaterialDao materialDao;
    private final PackDao packDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        materialDaoConfig = daoConfigMap.get(MaterialDao.class).clone();
        materialDaoConfig.initIdentityScope(type);

        packDaoConfig = daoConfigMap.get(PackDao.class).clone();
        packDaoConfig.initIdentityScope(type);

        materialDao = new MaterialDao(materialDaoConfig, this);
        packDao = new PackDao(packDaoConfig, this);

        registerDao(Material.class, materialDao);
        registerDao(Pack.class, packDao);
    }
    
    public void clear() {
        materialDaoConfig.getIdentityScope().clear();
        packDaoConfig.getIdentityScope().clear();
    }

    public MaterialDao getMaterialDao() {
        return materialDao;
    }

    public PackDao getPackDao() {
        return packDao;
    }

}
